version: "3.7"

services:

    service_1:
        image: service1:latest
        build: ./service1
        ports: 
            - "5000:5000"
        networks:
            - servicenetwork

    service_2:
        image: service2:latest
        build: ./service2
        ports: 
            - "5001:5001"
        networks:
            - servicenetwork

    service_3:
        image: service3:latest
        build: ./service3
        ports: 
            - "5002:5002"
        networks:
            - servicenetwork

    service_4:
        image: service4:latest
        build: ./service4
        ports: 
            - "5003:5003"
        networks:
            - servicenetwork

networks:
    servicenetwork:
        driver: bridge
