version: "3.7"

services:

    service_1:
        
        # put environment variables for the mysql server here
        image:
            finn969/sfia-2:service_1
        ports: 
            - "80:5000"
        networks:
            - servicenetwork
        deploy:
            replicas: 3

    service_2:
        
        image:
            finn969/sfia-2:service_2
        ports: 
            - "5001:5001"
        networks:
            - servicenetwork
        deploy:
            replicas: 3

    service_3:
        
        image:
            finn969/sfia-2:service_3
        ports: 
            - "5002:5002"
        networks:
            - servicenetwork
        deploy:
            replicas: 3

    service_4:
        
        
        image:
            finn969/sfia-2:service_4
        ports: 
            - "5003:5003"
        networks:
            - servicenetwork
        deploy:
            replicas: 3

    service_nginx:
        image: nginx:latest
        ports: :
            - "80:80"
        networks:
            -servicenetwork
        depends_on: 
            -service_1
            -service_2
            -service_3
            -service_4
        deploy:
            replicas: 1
            


networks:
    servicenetwork:
        driver: overlay
