version: "3.7"

services:

    service_1:
        
        image:
            finn969/sfia-2:service_1
        ports: 
            - "80:5000"
        networks:
            - testnetwork

    service_2:
        
        image:
            finn969/sfia-2:service_2
        ports: 
            - "5001:5001"
        networks:
            - testnetwork

    service_3:
        
        image:
            finn969/sfia-2:service_3
        ports: 
            - "5002:5002"
        networks:
            - servicenetwork

    service_4:
        
        image:
            finn969/sfia-2:service_4
        ports: 
            - "5003:5003"
        networks:
            - servicenetwork

    service_nginx:
        image: nginx:latest
        ports: :
            - "80:80"
        networks:
            -testnetwork
        depends_on: 
            -service_1
            -service_2
            -service_3
            -service_4

networks:
    testnetwork:
        driver: overlay
