---
- name: Install Docker
  hosts: localhost
  connection: local
  become: true
  roles:
    - docker-installation
# This process was intended to be run on a separate manager node
- name: Initialise Docker Swarm
  hosts: localhost
  become: true
  roles:
    - docker-swarm-init

# Unable to implement worker nodes
#- name: add workers
#  hosts: swarm-workers
#  become: true
#  roles:
#    - docker-swarm-add-workers
  